Martin/insturen foto 02
WouterRBerkhout/BACK-VVE-app-ipsen5 pull request #4
Opened 2022-05-18 19:13 UTC by MartinVeltman

2022-05-23 07:13 UTC, WouterRBerkhout requested changes

2022-05-23 07:13 UTC, WouterRBerkhout commented on src/main/java/nl/dwd/backvveappipsen5/controllers/ImageController.java
> +        return MessageResponse.generateResponse("Image succesvol ingediend", HttpStatus.OK, null);
Front end creates its own version of this string in the Toastr pretty sure, should probably return this response.

2022-05-23 07:13 UTC, WouterRBerkhout commented on src/main/java/nl/dwd/backvveappipsen5/models/Image.java
> +}
PLEASE use Lombok, instead of getters and setters type @Getter and @Setter above the class declaration!

2022-05-23 07:13 UTC, WouterRBerkhout commented on src/main/java/nl/dwd/backvveappipsen5/models/Ticket.java
> +    private long id;
Why are we changing this to a long?

2022-05-23 22:06 UTC, MartinVeltman commented on src/main/java/nl/dwd/backvveappipsen5/controllers/ImageController.java
> +        return MessageResponse.generateResponse("Image succesvol ingediend", HttpStatus.OK, null);
return what exactly?

2022-05-23 22:08 UTC, MartinVeltman commented on src/main/java/nl/dwd/backvveappipsen5/controllers/ImageController.java
> +        return MessageResponse.generateResponse("Image succesvol ingediend", HttpStatus.OK, null);
it's nice to have a response from the backend aswell tho

2022-05-25 10:16 UTC, WouterRBerkhout commented
Pretty sure the repository still takes a Long instead of a UUID

2022-05-31 10:10 UTC, merged